version: "3"
services:
  dev:
    image: goblinql
    container_name: goblin-prod
    ports:
    - 3000:3000
    volumes:
    - ./:/usr/src/app
    - node_modules:/usr/src/app/node_modules
    command: npm start
volumes:
  node_modules: