version: "3"
services:
  dev:
    image: inquery-website
    container_name: inquery-dev-hot
    ports:
    - 8080:8080
    - 3000:3000
    volumes:
    - ./:/usr/src/app
    - node_modules:/usr/src/app/node_modules
    command: npm run dev
volumes:
  node_modules: